### ISSUE TITLE
Website should ideally be full width and not boxed in between

### ISSUE THREAD

**Issue by sudheesh001** [loklak/loklak.github.io#3]
Currently the website looks like this

<img width="1440" alt="screen shot 2016-04-07 at 5 18 49 pm" src="https://cloud.githubusercontent.com/assets/4545925/14350091/d8d57c66-fce4-11e5-9911-7b2373fe3ef3.png">

It should look like this instead from a design perspective. (with the margin borders removed)

<img width="1440" alt="screen shot 2016-04-07 at 5 19 00 pm" src="https://cloud.githubusercontent.com/assets/4545925/14350090/d853b1ae-fce4-11e5-9489-77fd98a612d1.png">

#### The fix that has to be made is
`theme.css` Line 98
```css
.boxed-layout .main-container,
.boxed-layout .nav-container,
.boxed-layout nav,
.boxed-layout .footer-container {
  /* max-width: 1366px; */
  left: 0;
  right: 0;
  margin: 0 auto;
}
```
Removing this [line](https://github.com/loklak/loklak.github.io/blob/master/css/theme.css#L102) or making it `100%` should solve this problem.

This is a beginner bug and intended to those getting started to contribute to loklak.

To those who are planning to fix this, also align the loklak cow logo in the navbar vertically in the center of  the navbar.
